=== kahheng98q/Php/XML/Stocks.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT stocks (stock*)>
<!ELEMENT stock (stockName, unitPrice,type,weightUnit,soldqty,mainTotalPrice)>
<!ATTLIST stock  stockid ID #REQUIRED>
<!ELEMENT stockName (#PCDATA)>
<!ELEMENT unitPrice (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT weightUnit (#PCDATA)>
<!ELEMENT soldqty (#PCDATA)>
<!ELEMENT mainTotalPrice (#PCDATA)>

=== kahheng98q/Php/XML/StockXML.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE stocks SYSTEM 'Stocks.dtd'>
<stocks>
    <stock stockid="ST001">
        <stockName>Bottle</stockName>
        <unitPrice>3.00</unitPrice>
        <type>Solid</type>
        <weightUnit>0.30</weightUnit>
        <soldqty>1</soldqty>
        <mainTotalPrice>1</mainTotalPrice>
    </stock>
    <stock stockid="ST002">
        <stockName>Book</stockName>
        <unitPrice>2.00</unitPrice>
        <type>Solid</type>
        <weightUnit>5.00</weightUnit>
        <soldqty>1</soldqty>
        <mainTotalPrice>1</mainTotalPrice>
    </stock>
</stocks>
