=== kahheng98q/Php/jackyAssignment/xml/orders.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--author: Chia Yang Jie-->
<!ELEMENT orders (order*)>
<!ELEMENT order (OrderDate, OrderStatus,TotalAmount,CustomerId)>
<!ATTLIST order  OrderID ID #REQUIRED>
<!ELEMENT OrderDate (#PCDATA)>
<!ELEMENT OrderStatus (#PCDATA)>
<!ELEMENT TotalAmount (#PCDATA)>
<!ELEMENT CustomerId (#PCDATA)>

=== kahheng98q/Php/XML/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orders SYSTEM 'orders.dtd'>
<orders><order OrderID="OO001"><OrderDate>2020-01-21</OrderDate><OrderStatus>COMPLET</OrderStatus><TotalAmount>50.00</TotalAmount><CustomerId/></order><order OrderID="OO002"><OrderDate>2020-01-21</OrderDate><OrderStatus>COMPLET</OrderStatus><TotalAmount>50.00</TotalAmount><CustomerId/></order><order OrderID="OO003"><OrderDate>2020-01-21</OrderDate><OrderStatus>COMPLET</OrderStatus><TotalAmount>50.00</TotalAmount><CustomerId/></order></orders>
